apiVersion: v1
kind: Service
metadata:
  namespace: grpc
  name: gok-server-headless
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: grpc
  selector:
    app: gok-server
