apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grpc
  name: gok-client-headless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gok-client-headless
  template:
    metadata:
      labels:
        app: gok-client-headless
    spec:
      containers:
        - name: gok-client
          image: mjpitz/grpc-on-kubernetes:latest
          imagePullPolicy: IfNotPresent
          args:
            - client
            - --target
            - dns:///gok-server-headless:8080
