apiVersion: v1
kind: Service
metadata:
  name: gok-server-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: grpclb
  selector:
    app: gok-server
